name: Compile ESP32-C3 LCD

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  compile:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repositori
        uses: actions/checkout@v4

      - name: Compile Arduino Sketch
        uses: arduino/compile-sketches@v1
        with:
          fqbn: esp32:esp32:esp32c3
          platforms: |
            - name: esp32:esp32
              source-url: https://raw.githubusercontent.com/espressif/arduino-esp32/gh-pages/package_esp32_index.json
          libraries: |
            - name: TFT_eSPI
          sketch-paths: |
            - esp32c3_lcd
          cli-compile-flags: |
            --export-binaries
            --build-property=compiler.cpp.extra_flags="-DUSER_SETUP_LOADED=1 -DST7789_DRIVER=1 -DTFT_WIDTH=76 -DTFT_HEIGHT=284 -DTFT_MOSI=6 -DTFT_SCLK=4 -DTFT_CS=7 -DTFT_DC=2 -DTFT_RST=1 -DLOAD_GLCD=1 -DLOAD_FONT2=1 -DLOAD_FONT4=1 -DSPI_FREQUENCY=27000000"
